In [ ]:
!pip install colour-science
!pip install matplotlib
!pip install numpy
!pip install pandas
!python -c "import imageio;imageio.plugins.freeimage.download()"

In [11]:
from pprint import pprint

In [10]:
import colour
import matplotlib.pyplot as plt
import numpy as np

In [15]:


pprint((colour.SDS_COLOURCHECKERS['ColorChecker N Ohta']))

LazyCanonicalMapping({'dark skin': SpectralDistribution([[  3.80000000e+02,   4.80000000e-02],
                      [  3.85000000e+02,   5.10000000e-02],
                      [  3.90000000e+02,   5.50000000e-02],
                      [  3.95000000e+02,   6.00000000e-02],
                      [  4.00000000e+02,   6.50000000e-02],
                      [  4.05000000e+02,   6.80000000e-02],
                      [  4.10000000e+02,   6.80000000e-02],
                      [  4.15000000e+02,   6.70000000e-02],
                      [  4.20000000e+02,   6.40000000e-02],
                      [  4.25000000e+02,   6.20000000e-02],
                      [  4.30000000e+02,   5.90000000e-02],
                      [  4.35000000e+02,   5.70000000e-02],
                      [  4.40000000e+02,   5.50000000e-02],
                      [  4.45000000e+02,   5.40000000e-02],
                      [  4.50000000e+02,   5.30000000e-02],
                      [  4.55000000e+02,   5.30000000e-02],
     

In [17]:
light_skin = colour.SDS_COLOURCHECKERS['ISO 17321-1']['light skin']
light_skin

SpectralDistribution([[  3.80000000e+02,   1.03000000e-01],
                      [  3.85000000e+02,   1.20000000e-01],
                      [  3.90000000e+02,   1.41000000e-01],
                      [  3.95000000e+02,   1.63000000e-01],
                      [  4.00000000e+02,   1.82000000e-01],
                      [  4.05000000e+02,   1.92000000e-01],
                      [  4.10000000e+02,   1.97000000e-01],
                      [  4.15000000e+02,   1.99000000e-01],
                      [  4.20000000e+02,   2.01000000e-01],
                      [  4.25000000e+02,   2.03000000e-01],
                      [  4.30000000e+02,   2.05000000e-01],
                      [  4.35000000e+02,   2.08000000e-01],
                      [  4.40000000e+02,   2.12000000e-01],
                      [  4.45000000e+02,   2.17000000e-01],
                      [  4.50000000e+02,   2.24000000e-01],
                      [  4.55000000e+02,   2.31000000e-01],
                      [  4.60000000e+02,

In [18]:
light_skin = colour.SDS_COLOURCHECKERS['ColorChecker N Ohta']['light skin']

In [19]:
ilm = colour.SDS_ILLUMINANTS['D65']

In [20]:
cmfs = colour.MSDS_CMFS.get('CIE 1931 2 Degree Standard Observer')


In [ ]:
shape = colour.SpectralShape(380, 780, 10)
light_skin = light_skin.align(shape)
light_skin = light_skin.align(shape)
ilm = ilm.align(shape)
cmfs = cmfs.align(shape)

In [65]:
colour.sd_to_XYZ(light_skin, cmfs, ilm)/100

array([ 0.38131443,  0.35591917,  0.25912804])

In [18]:
colour.sd_to_XYZ(light_skin, cmfs)

array([ 41.21940797,  36.32599917,  23.6194468 ])

In [19]:
colour.sd_to_XYZ(light_skin, cmfs, method='ASTM E308', shape = shape)

array([ 41.21940797,  36.32599917,  23.6194468 ])

In [21]:
sd = light_skin * ilm

In [28]:
colour.sd_to_XYZ(sd, cmfs, method='Integration', shape = shape)

array([ 36.96067725,  34.49888496,  25.13173598])

In [ ]:
colour.sd_to_XYZ(sd, cmfs, method='ASTM E308', shape = shape)

In [32]:
colour.sd_to_XYZ(light_skin, cmfs, ilm, method='Integration', shape = shape)

array([ 38.12845232,  35.58887954,  25.92577486])

In [35]:
colour.colorimetry.sd_to_XYZ_integration(sd)

array([ 36.96917732,  34.49904588,  25.16134478])

In [61]:
cmfs_sds = cmfs.to_sds()

x = sd * cmfs_sds[0] *10
X =np.sum(x.values)
X

39.495363955283715

In [63]:
y = sd * cmfs_sds[1] *10
Y = np.sum(y.values)
Y

36.864747047591706

In [64]:
z = sd * cmfs_sds[2] *10
Z = np.sum(z.values)
Z

26.855218384793606

In [66]:
colour.colorimetry.sd_to_XYZ_integration(sd)

array([ 36.96917732,  34.49904588,  25.16134478])

In [79]:
XYZ = colour.colorimetry.sd_to_XYZ_integration(sd)/100

In [71]:
srgb = colour.XYZ_to_sRGB(XYZ)
srgb

array([ 0.76252692,  0.58328168,  0.50229251])

In [72]:
colorspace = colour.RGB_COLOURSPACES['sRGB']

In [75]:
m = colorspace.matrix_XYZ_to_RGB
m

array([[ 3.2406, -1.5372, -0.4986],
       [-0.9689,  1.8758,  0.0415],
       [ 0.0557, -0.204 ,  1.057 ]])

In [81]:
rgb = m@XYZ
rgb

array([ 0.54224936,  0.2993807 ,  0.21616919])